// Inlines the browser-side files into modules the worker can serve. Workers
// have no filesystem, and keeping these as real .js/.html files means they stay
// lintable and readable instead of living inside a template literal.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const targets = [
  ['client/injector.js', 'src/generated/injector-source.js'],
  ['client/admin.html', 'src/generated/admin-html.js'],
];

for (const [from, to] of targets) {
  const source = readFileSync(resolve(root, from), 'utf8');
  const out = resolve(root, to);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(
    out,
    `// Generated by tools/build-client.mjs from ${from} -- do not edit.\nexport default ${JSON.stringify(source)};\n`,
  );
  console.log(`built ${to} (${source.length} bytes)`);
}
